import type { Metadata } from "next";
import { Inter } from "next/font/google";
import cn from "@/utils/cn";
import "./globals.css";

const inter = Inter();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn([inter.className, "bg-base-300"])}>{children}</body>
    </html>
  );
}
